class student:
    crs="python"
s1=student()
s2=student()
print("content of s1 before adding=",s1.__dict__)
print("content of s2 before adding=",s2.__dict__)
print("_"*20)
print("first student information")
print("_"*30)
s1.sno=int(input("enter student number:"))
s1.sname=input("enter student name:")
s1.marks=float(input("enter student marks:"))
print("-"*20)
print("second student information")
print("_"*20)
s2.sno=int(input("enter stydent number:"))
s2.sname=input("enter student name:")
s2.marks=float(input("enter student student marks:"))
print("_"*30)
print("first student information")
print("student number=",s1.sno)
print("student nme=",s1.sname)
print("student marks=",s1.marks)
print("student course=",student.crs)
print("_"*30)
print("second student information")
print("student number=",s2.sno)
print("student nme=",s2.sname)
print("student marks=",s2.marks)
print("student course=",s2.crs)
